### ISSUE TITLE
to_metric / to_inch is not idempotent

### ISSUE THREAD

**Issue by punkkeks** [curtacircuitos/pcb-tools#25]
```
In [58]: b.to_metric()

In [59]: b.lower_left
Out[59]: (998.89, 1904.43)

In [60]: b.to_metric()

In [61]: b.lower_left
Out[61]: (25386.446, 48386.43)

In [62]: b.to_metric()

In [63]: b.lower_left
Out[63]: (644830.3683999999, 1229029.23)

In [64]: b.to_metric()

In [65]: b.lower_left
Out[65]: (16378705.997359997, 31217356.349999998)
```

This is a problem. A fix would be to store internally what unit is currently in use.

**Comment by phsilva** [comment]
@punkkeks, I will take a look at it. Thanks for the catch.

**Comment by phsilva** [comment]
Fixed by #25. Thanks.

**Comment by punkkeks** [comment]
@phsilva please look at my comment 
https://github.com/curtacircuitos/pcb-tools/commit/390838fc8b70c9b105fdc1d3e35a4533b27faa83#commitcomment-10892665

**Comment by punkkeks** [comment]
I would suggest, that you store all variables that need to be converted in a list as 'private member' (or similar) and convert these in the to_metric method in the primitive class... This could be easier and reduce the code a lot!

**Comment by phsilva** [comment]
yep, it will reduce much of the code. will add this to my (growing) refactoring list. tks.

**Comment by hamiltonkibbe** [comment]
I like that approach, I'll go ahead and make that change, along with making sure all the tests cover regression on this issue
