### ISSUE TITLE
Svgwrite and cairo merge issues

### ISSUE THREAD

**Issue by CreativeSoftware** [curtacircuitos/pcb-tools#33]
After the merge I faced some issues. When I try load 2 or more layers on the same ctx dumping in the end to a png it only appears the last load, the first ones didn’t load.
When I try to use svg as output I have a problem probably because I’m using windows. It is prompted a problem on a temporary file and the svg it is not created.

**Comment by phsilva** [comment]
@CreativeSoftware, could you try the latest version and see if it is solved? Just this particular issue for now.

**Comment by CreativeSoftware** [comment]
The layers are been rendering properly overlaid ! Well done.

However, it is not working the svg.
 File "build\bdist.win-amd64\egg\gerber\cam.py", line 264, in render
  File "build\bdist.win-amd64\egg\gerber\render\cairo_backend.py", line 157, in dump
IOError: [Errno 13] Permission denied: 'c:\\users\\marcoe~1\\appdata\\local\\temp\\tmpx0icyj'

**Comment by hamiltonkibbe** [comment]
@CreativeSoftware could you confirm that the permissions error is fixed with the last commit?

**Comment by CreativeSoftware** [comment]
Svg writing permissions solved!

**Comment by hamiltonkibbe** [comment]
@phsilva we should be able to close this, as it is specific to the cairo-render-unification branch, but I'm not sure if you want to wait until the branch is merged into master

**Comment by phsilva** [comment]
@hamiltonkibbe, we can close, I will finish the work on the cairo-render-unification to get it ready to merge.

**Comment by hamiltonkibbe** [comment]
Sounds good. Closing
