### ISSUE TITLE
Do not read solely from files

### ISSUE THREAD

**Issue by punkkeks** [curtacircuitos/pcb-tools#37]
When parsing a (e.g.) gerber file, you have to have a file, but in my current situation I already read the file because of internal file handling.
I'd like to have a function where you can pass the data and get the result back (I hope you undestand what I want, i can't express myself today :/ )

**Comment by hamiltonkibbe** [comment]
Would the data be in a string or some other format (open file handle, etc.)?

**Comment by punkkeks** [comment]
in my case a bytearray, but a string would be perfectly fine as well.

**Comment by hamiltonkibbe** [comment]
@punkkeks Could you take a look at the read_from_memory branch and see if that works for your use case?

**Comment by punkkeks** [comment]
Looks good to me. I tried to load the file (why do you call it loads?), get the primitives out and render an image. Works :) No Exceptions for me, so I give it a :+1:

**Comment by hamiltonkibbe** [comment]
Probably too much messing around with the JSON module which uses load() for files and loads() for strings

**Comment by phsilva** [comment]
fixed by #41

**Comment by phsilva** [comment]
let me know if there is anything else on this issue, otherwise I'll close it.
