### ISSUE TITLE
Semitransparent layer

### ISSUE THREAD

**Issue by sergeyfedotov** [curtacircuitos/pcb-tools#50]
Is it possible to draw a semitransparent solder mask over the copper layer?

Like this:
![7b0028f977275872af9b531cc4ad9b98](https://cloud.githubusercontent.com/assets/2290214/11763726/8dbf78c2-a126-11e5-9cb7-1653b2013ae1.png)

**Comment by hamiltonkibbe** [comment]
You can set the ```alpha``` parameter on the rendering context to set layer opacity, but at the moment we don't have the ability to render the soldermask layer in negative....

I'll take a look at this, shouldn't be too difficult to add

**Comment by phsilva** [comment]
Fixed per #50. Would be nice if you could check and maybe post an image here from your use case. Thanks.

**Comment by sergeyfedotov** [comment]
Thx, it works fine

![cairo_example](https://cloud.githubusercontent.com/assets/2290214/11928395/4958df1a-a7e4-11e5-940b-edd8fecea4f3.png)
