### ISSUE TITLE
Regex for guess_layer_class

### ISSUE THREAD

**Issue by ju5t** [curtacircuitos/pcb-tools#61]
Unfortunately not everyone uses the same naming convention. I tried adding hints by extending layers.hints but the regex that is used there is too specific for the files I want to match. I'd like to extend guess_layer_class as follows (and as such change `Hint = namedtuple('Hint', 'layer ext name')` into `Hint = namedtuple('Hint', 'layer ext name regex')`:

```
def guess_layer_class(filename):
    try:
        directory, name = os.path.split(filename)
        name, ext = os.path.splitext(name.lower())
        for hint in hints:
            if hint.regex:
                if re.findall(hint.regex, name, re.IGNORECASE):
                    return hint.layer
            
            patterns = [r'^(\w*[.-])*{}([.-]\w*)?$'.format(x) for x in hint.name]
            if ext[1:] in hint.ext or any(re.findall(p, name, re.IGNORECASE) for p in patterns):
                return hint.layer
    except:
        pass
    return 'unknown'
```

I don't want to change the regex that is used in `patterns` because if it would not be specific it would currently match *top* for example which could be anything really.

If you're alright with this I can create a pull request for it.

**Comment by hamiltonkibbe** [comment]
Yeah that looks good, go ahead an open a PR. Adding some test cases with the filenames that were giving you trouble would rock
