### ISSUE TITLE
Drill files with Gxx commands on their own line crash the gerber parser

### ISSUE THREAD

**Issue by gadgetjunkie** [curtacircuitos/pcb-tools#66]
The following is valid Excellon:

G00
X040944Y019842
M15
G01
X040944Y020708
M16

The parser for the G00 and G01 commands assume that the coordinates follow the routing command on the same line.  When parsing excellon code like the example, this results in an index out of range exception in from_excellon because an empty string has been passed to it.

Need to add checks for empty string in from_excellon and separate the coordinate processing from the G00/G01 command processing.

**Comment by hamiltonkibbe** [comment]
Fixed by 7ad6c3f
