### ISSUE TITLE
Creating a custom render class still requires Cairo

### ISSUE THREAD

**Issue by sybrenstuvel** [curtacircuitos/pcb-tools#83]
I'm trying to use pcb-tools to create an importer for [Blender](https://www.blender.org/). The approach I'm thinking of is to create a custom renderer that actually generates Blender geometry. However, when importing `gerber.render` it fails because that module tries to import `.cairo_backend`.

By automatically importing that module, Cairo is always a requirement, even when it's not used at all.

To reproduce this issue, just run `import gerber.render.render` in a Cairo-less environment.

**Comment by hamiltonkibbe** [comment]
Yeah cairo has been the de-facto renderer for a while, extensibility needs a bit of love and documentation. Check with 5245fb9 and see if that works for you
