### ISSUE TITLE
CamFile.render() calls ctx functions not defined on GerberContext

### ISSUE THREAD

**Issue by sybrenstuvel** [curtacircuitos/pcb-tools#84]
`CamFile.render()` unconditionally calls the following methods on `ctx` that are not defined on `GerberContext`: 

```
        ctx.set_bounds(self.bounding_box)
        ctx._paint_background()
        ctx._new_render_layer()
        ctx._flatten()
```

Having those functions not defined on the class that is intended to be subclassed seems like bad design to me.

**Comment by hamiltonkibbe** [comment]
Would like to add some documentation about how to extend this stuff, but i've added stubs for those to the base class... maybe moving to an ABC at some point. let me know if 5245fb9 fixed this for you
