### ISSUE TITLE
Document supported Gerber/Excellon constructs and render status

### ISSUE THREAD

**Issue by phsilva** [curtacircuitos/pcb-tools#9]
Table with construction (gerber and excellon) status: parsing, creation, transform (currently only inch2metric and metric2inch, later rotation and maybe general transforms) and render.

**Comment by hamiltonkibbe** [comment]
I'll put a features page into the docs with a table like that. I'll get the repo set up on readthedocs as well.

**Comment by phsilva** [comment]
Fixed by bc53299, closing.
